packages:
  # todos os pacotes em subdiret처rios diretos de packages/
  - 'packages/*'
  # todos os pacotes em subdiret처rios de components/
  - 'components/**'
  # exclui pacotes que est찾o dentro dos diret처rios de teste
  - '!* */teste/**'